export const GET_LEADS = { type: "LEADS", url: '/lms/lead/' }
export const GET_LEAD_INFORMATION = { type: "LEAD_INFO", url: '/lms/lead/' }
export const GET_EQUIPMENT_SUPPLIER_LIST = { type: 'SUPPLIER_LIST', url: '/lms/supplierList' }
export const GET_LEAD_EQUIPMENT_DETAILS = { type: "LEAD_EQUIPMENT_DETAILS", url: '/lms/lead/' }
export const CHANGE_LEAD_STATUS = { type: "CHANGING_LEAD_STATUS", url: '/lms/changeLeadStatus' }
export const CHANGE_SERVICE_STATUS = { type: "CHANGING_SERVICE_STATUS", url: '/lms/changeServiceStatus' }
export const MAKE_A_REQUEST_BID = { type: "REQUEST_BID", url: '/lms/requestBid/' }
export const MOVE_TO_PROJECTS = { type: "MOVING_TO_PROJECTS", url: '/lms/moveToProjects' }
export const PROJECT_LIST_NUCLEUS = {type:"LIST_OF_PROJECTS_IN_NUCLEUS", url:'/lms/projects/new'}
export const GET_EQUIPMENT_SUPPLIER_DETAILS = {type:"GET_SUPPLIER_DETAILS", url:'/lms/supplierDetails'}
export const CREATE_LEAD = {type:"CREATE_A_NEW_LEAD", url:'/lms/lead/'}
export const GET_STATES = {type:"GET_STATES", url:'/lms/getStates'}
export const GET_CITIES = {type:"GET_CITIES", url:'/lms/getCities/'}